export const CAREERS = [
  {
    position: 'Chief Technology Officer (CTO)',
    company: 'Vesatogo Innovations',
    logo: '/images/careers/vesatogo.png',
    location: 'Nashik',
    location_type: 'hybrid',
    type: 'Fulltime',
    start_date: '2023-08',
    end_date: null,
    industry: 'agritech',
    link: 'https://www.linkedin.com/company/vesatogo/',
  },
  {
    position: 'Senior Software Developer',
    company: 'Vesatogo Innovations',
    logo: '/images/careers/vesatogo.png',
    location: 'Nashik',
    location_type: 'hybrid',
    type: 'Fulltime',
    start_date: '2022-01',
    end_date: '2023-08',
    industry: 'agritech',
    link: 'https://www.linkedin.com/company/vesatogo/',
  },
  {
    position: 'React Developer',
    company: 'Razrtech',
    logo: '/images/careers/razrtech.png',
    location: 'Mumbai',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-01',
    end_date: '2021-10',
    industry: 'e-commerce',
    link: 'https://www.linkedin.com/company/razrtech/',
  },
  {
    position: 'Junior Software Developer',
    company: 'Vesatogo Innovaions',
    logo: '/images/careers/vesatogo.png',
    location: 'Nashik',
    location_type: 'office',
    type: 'Fulltime',
    start_date: '2019-05',
    end_date: '2021-01',
    industry: 'agritech',
    link: 'https://www.linkedin.com/company/vesatogo/',
  },
];
