import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Full Stack Engineer',
    company: 'Freelance',
    location: 'Nashik, India 🇮🇳',
    location_type: 'remote',
    type: 'Fulltime',
    start_date: '2024-06',
    end_date: null,
    industry: 'freelance',
    link: 'https://www.linkedin.com/in/malikbagwala/',
    company_legal_name: 'maalik.dev',
    logo: null,
    responsibilities: [],
  },
  {
    position: 'Chief Technology Officer (CTO)',
    company: 'Vesatogo Innovations',
    logo: '/images/careers/vesatogo.png',
    company_legal_name: 'Vesatogo Innovations Pvt. Ltd.',
    location: 'Nashik, India 🇮🇳',
    location_type: 'onsite',
    type: 'Fulltime',
    start_date: '2023-08',
    end_date: '2024-06',
    industry: 'agritech',
    link: 'https://www.linkedin.com/company/vesatogo/',
    responsibilities: [],
  },
  {
    position: 'Senior Software Developer',
    company: 'Vesatogo Innovations',
    logo: '/images/careers/vesatogo.png',
    company_legal_name: 'Vesatogo Innovations Pvt. Ltd.',
    location: 'Nashik, India 🇮🇳',
    location_type: 'onsite',
    type: 'Fulltime',
    start_date: '2022-01',
    end_date: '2023-08',
    industry: 'agritech',
    link: 'https://www.linkedin.com/company/vesatogo/',
    responsibilities: [],
  },
  {
    position: 'React Developer',
    company: 'Razrcorp',
    company_legal_name: 'Razrtech Pvt. Ltd.',
    logo: '/images/careers/razrtech.png',
    location: 'Mumbai, India 🇮🇳',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-01',
    end_date: '2021-10',
    industry: 'e-commerce',
    link: 'https://www.linkedin.com/company/razrtech/',
    responsibilities: [],
  },
  {
    position: 'Junior Software Developer',
    company: 'Vesatogo Innovaions',
    logo: '/images/careers/vesatogo.png',
    company_legal_name: 'Vesatogo Innovations Pvt. Ltd.',
    location: 'Nashik, India 🇮🇳',
    location_type: 'onsite',
    type: 'Fulltime',
    start_date: '2019-05',
    end_date: '2021-01',
    industry: 'agritech',
    link: 'https://www.linkedin.com/company/vesatogo/',
    responsibilities: [],
  },
];
